.SILENT:

VMFILES = vmdplumed.tcl pkgIndex.tcl \
	  templates_list_v1.tcl templates_list_v2.tcl
VMVERSION = 2.4
DIR = $(PLUGINDIR)/noarch/tcl/plumed$(VMVERSION)


default: autogen


bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:


# The first targets are used by VMD's builds.

# When changing VMVERSION version number, also fix it in
# vmdplumed.tcl, templates_list_v1.tcl, and in
# gentemplate/generate_templates_list_v2.tcl (until I find a better
# way)

# This target and the ones above need run successfully with
# pre-distributed files (i.e. when the user doing make distrib can't
# run autogen). The dependency on autogen is set only to make sure the
# autogenerated files are present.
distrib: autogen
	@echo "Copying plumed $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 


# export
.PHONY:
autogen: 
	make -f maintainer/Makefile


