# This -*- Makefile -*- requires plumed 2.0

default: templates_list_v2_autogen.tcl pkgIndex.tcl

templates_list_v2_autogen.tcl: gentemplate/generate_templates_list_v2.tcl
	tclsh $< > $@


#  $(VMFILES) sans pkgIndex itself
pkgIndex.tcl: templates_list_v1.tcl templates_list_v2_autogen.tcl vmdplumed.tcl
	tclsh <<< "pkg_mkIndex -verbose ."

.PHONY:
clean:
	-rm templates_list_v2_autogen.tcl pkgIndex.tcl


